metadata:
  name: strongDM Docs
  rootTitleTag: "strongDM Content Style Guide"
  titleTagSuffix: "| strongDM Content Style Guide"
  short_name: sdmstyle
  description: Get started with strongDM.
  language: en
  url: 'https://www.strongdm.com'
  pathPrefix: /style
  assetPrefix: /
  gaTrackingId: null
  gtmId: GTM-WH42NPH
  favicon: /images/favicon-docs.png
  themeColor: '#0066cc'
header:
  enabled: true
  helpUrl: ""
  logo: https://uploads-ssl.webflow.com/5ecfe3add0194393eabdf182/5fb8da491f61a6151f280c27_strongDM-logo.svg
  logoLink: /
  logo2: https://www.strongdm.com/images/logo3.svg
  logoLink2: /
  trialButtonLink: https://www.strongdm.com/docs
  trialButtonText: View the Docs
  not_links:
    - text: Docs
      link: https://www.strongdm.com/docs
    - text: Education
      link: https://sites.google.com/strongdm.com/education
  links: {}
sidebar:
  enabled: true
  groups:
    - order: 1
      path: "/installation"
      title: Installation
    - order: 2
      path: "/admin-ui-guide"
      title: Admin UI Guide
  ignoreIndex: false
  forcedNavOrder:
    - "/architecture"
    - "/architecture/strongdm-architecture"
    - "/architecture/deployment"
    - "/architecture/authorization"
    - "/architecture/authorization/users-and-roles"
    - "/architecture/authorization/authentication"
    - "/architecture/authorization/strong-permissions"
    - "/architecture/security"
  notexpanded:
    - "/installation"
    - "/admin-ui-guide"
    - "/automation"
    - "/api"
    - "/cli"
    - "/user-guide"
    - "/release-notes"
  frontLine: false
  not_links:
    - text: Merriam-Webster Dictionary
      link: https://m-w.com/
  poweredBy: {}
pwa:
  enabled: false
  manifest:
    icon: /assets/logo.png
    display: minimal-ui
    crossOrigin: anonymous
features:
  publishDraft: false
  editOnRepo:
    editable: false
    location: 'https://github.com/domarty/boogi'
    type: github
  rss:
    enabled: false
    showIcon: true
    copyright: ''
    categories: []
    matchRegex: ^/
    outputPath: /rss.xml
  darkMode:
    enabled: true
    default: false
  mermaid:
    language: "mermaid" # language descriptor used
    theme: "dark" # diagram color theme. Choose one from: dark, neutral, forest, default.
    options: # additional configuration options
    width: 300 # desired viewport width while rendering the SVG
    height: 300 # desired viewport height while rendering the SVG
  pageProgress:
    enabled: true # set to true to enable
    includePaths: # list of paths for which page progress should be visible
      - "/" # it can be simple string
    height: 3 # height in pixels of the progress bar
    prependToBody: true # set to true to prepend progress bar to <body>, otherwise append it
    color: "#A05EB5" # color of the progress bar. As of now light/dark mode themes are not supported
  scrollTop: false
  search:
    enabled: true
    engine: algolia
    indexName: sdm
    algoliaAppId: D8N5TH1LTK
    algoliaSearchKey: f25e264a5a7683aef6ad0a4ea4018735
    algoliaAdminKey: abd4239e6860a576f6b3b47ca358a9e1
    excerptSize: 10000
    snippetLength: 22
    hitsPerPage: 15
    startComponent: icon
    placeholder: Search
  pagination:
    enabled: true
    totalpages: 10
    showNext: true,
    showPrevious: true
  fullScreenMode:
    enabled: false
    hideHeader: true
    hideSidebar: true
    hideToc: true
