# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'sdmdocs':
  name: sdmdocs
  long_name: strongDM Docs
  description: Get started with strongDM.
